[package]
name = "bevytut"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = "0.6"
rand = "0.8"
clap="3.0.*"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=off"]

[workspace]
resolver = "2" # Important for wgpu/Bevy, but why?